Favetti/hadesbotty

commands/help.js
commands/searchtech.js
commands/setalltech.js
commands/settech.js
index.js
modules/tech.js

Adds some common aliases for some tech modules
Allows spaces between levels when using setalltech
Adds the prefix to the usage examples in help

A couple changes (untested)

---

commands/searchtech.js

fix searchtech command

---

commands/lastseen.js
commands/techreport.js
events/message.js
modules/functions.js

Added new command 'techreport'
Added error logging be default to message event where it runs commands

Adding techreport Command

---

commands/searchtech.js

Fixing Techreport Role

---

modules/functions.js

More aliases

---

commands/roster.js
index.js

Adding the Roster command for use in WS planner

Roster command

---

commands/roster.js

Fixing the Roster command for use in WS planning

Add ship level, remove debug

---

commands/redstar.js
commands/roster.js
index.js

Fixing Roster persistence and adding Redstar Command

Fixing Roster persistence and adding Redstar Command

---

commands/redstar.js
commands/roster.js

Fixing Roster persistence and adding Redstar Command

fixes and improvements to RS Que and WS Roster

---

commands/roster.js

disabling RESET on ROSTER

---

commands/gettech.js
commands/reddit.js
commands/searchtech.js
commands/setalltech.js
commands/settech.js
commands/stats.js
commands/tech.js
commands/techreport.js
commands/techscore.js
commands/time.js

Deprecate old commands, minor fixes

---

commands/export.js
commands/gettech.js
commands/help.js
commands/lastseen.js
commands/mylevel.js
commands/ping.js
commands/reboot.js
commands/reddit.js
commands/redstar.js
commands/roster.js
commands/searchtech.js
commands/setalltech.js
commands/settech.js
commands/tech.js
commands/techreport.js
commands/techscore.js

Cleaner Help

---

commands/audit.js
commands/eval.js
commands/export.js
commands/help.js
commands/invite.js
commands/mylevel.js
commands/reddit.js
commands/redstar.js
commands/reload.js
commands/roster.js
commands/set.js
commands/stats.js
commands/tech.js
commands/techreport.js
config.js
modules/functions.js

Tech get table and Help improving

---

commands/roster.js

showing 8 commints behind.... should be the same

fix branch

---

commands/tech.js

fix tech get table

---

commands/audit.js
commands/redstar.js
commands/tech.js
help/levelDB-structure.json
modules/functions.js

updateDisplayName function

---

commands/export.js
commands/lastseen.js
commands/roster.js
commands/stats.js
commands/tech.js
commands/techreport.js
commands/time.js
config.js
events/message.js
modules/functions.js

displayname GET/SET functions and minor improvements

---

config.js

bugfix techsize

---

commands/redstar.js
commands/settech.js
commands/tech.js
commands/time.js
config.js
modules/tech.js
shrinkwrap.yaml

Redstar update - 4man

---

config.js

Added Dart and Dispatch, Updated Number of Techs

---

commands/settech.js

Updated the tech list to include the new mods.

Added new techs

---

commands/tech.js

Changed info to account for new mods.

Update number of techs.

---

modules/tech.js

Added alternate names for the new weapon.

Added Case for Dart Names

---

commands/activity.js
commands/audit.js
commands/export.js
commands/invite.js
commands/lastseen.js
commands/mylevel.js
commands/redstar.js
commands/removetech.js
commands/roster.js
commands/tech.js
commands/techreport.js
commands/time.js
commands/whitelist.js
config.js
package.json

I have corrected and checked the English usage across most of the messages. I have also updated the "tech" help section.

Language updates.

---

commands/lastseen.js
commands/time.js

Fixed off by one error in loop
